security:
  oauth2:
    client:
      client-id: ENC(sNzVvZlhp5WJqfkkmAvVtPTSl0v1OLmY7vLQ0bhcuFQ=)
      client-secret: ENC(Pd1muVHlmTOIqtZFwHgivLUyPqWAazLb/6pp+h+6HCM=)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: JunHeRoot123!
    url: jdbc:mysql://tobacco.mysql.junhe:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /log/**
    - /talk/**
    - /online/info/**
    - /online/**
