security:
  oauth2:
    client:
      client-id: ENC(SDWRbevZTNcuwYwNbeyLPiWf4OI5wEyN)
      client-secret: ENC(78KHENwIGQhsTGQkWUD47EWBH6BqUe9r)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: JunHeRoot123!
    url: jdbc:mysql://tobacco.mysql.junhe:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /log/**
    - /payment/create
    - /payment/notify
    - /payment/remote/**

